repos:
    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.14.0
      hooks:
          - id: pretty-format-kotlin
            args: [--ktfmt, --ktfmt-style=google]
            files: ^.*\.kt$